### PR TITLE
Remove extraneous debug from Package.swift + fix Memory Leak

### PR DESCRIPTION
**Pull request by mattcolegate**
As well as removing debugging code from Package.swift, this pull requests also contains a fix for a memory leak - the calls to createAsciiString() and createNativeString() in APIConnector caused memory to be allocated that was not deallocated. Deallocation of memory now explicitly happens in APIConnector.

### CODE REVIEW

**Comment by mattcolegate** [comment]
This Pull request now also contains fixes for Work Item 119119

**Review by sjanuary — COMMENTED** [review]
Might be good to either change the title of this PR to reflect the fact that it also contains a bug fix, or to split the changes into 2 PRs.  Also probably better to describe the problem being solved than to reference an issue on a private bug tracking system that not everyone can see.

**Comment by mattcolegate** [comment]
Changed title and updated description.

**Comment by sjanuary** [comment]
Looks much better, thanks.

**Comment by tobespc** [comment]
LGTM

**Pull request merged**
